### ISSUE TITLE
[Windows] - Tape videos from Android slowed down

### ISSUE THREAD

**Issue by dac09** [edamameldn/tape-cli#27]
This seems to be related to the way Android sims process the recorded video. On mac, we need to slow it down - because the raw output is quite fast.

Checklist to understand the issue better:
- [ ] Does window record emulator at normal speed?
- [x] Does linux record emulator at normal speed?

If the double speed issue is mac only, we should apply the ffmpeg filter only on mac

**Comment by ingmaras** [comment]
From Alex:
emulator is sped up
usb device is slowed down

**Comment by dac09** [comment]
Confirmed on Linux, 
it seems like the speed up of the video does not happen on Linux 
```
Android Debug Bridge version 1.0.41
Version 29.0.6-6198805
```
