### ISSUE TITLE
EXDEV: cross-device link not permitted

### ISSUE THREAD

**Issue by danielzzz** [edamameldn/tape-cli#52]
hello, I've been trying to record a vid on my pc and I am gettingt the following error:

 Error:
 ```
tape gif --local=./ --format=md
 📱 Device: [android] herolte (samsung, SM-G930F, heroltexx, universal8890) - SDK 26 (ad0617020ca188820a)
Recording started in /tmp/LocativeDupGranulateInhalation-raw.mp4.
 
File saved and ready to upload!
 📼 Processing your tape... done
 🚴🏽‍♀️ Making your gif...... ✔️
 ›   Error: EXDEV: cross-device link not permitted, rename 
 ›   '/tmp/LocativeDupGranulateInhalation.gif' -> 
 ›   'LocativeDupGranulateInhalation.gif'


``` 
from what I've seen this error happens when trying to rename across partitions.
in my case /tmp and my project dir are on two different disks (hope it helps)

---
 - **os**: linux / DISTRIB_DESCRIPTION="Ubuntu 18.04.5 LTS"
- **arch**: x64 

thanks! dan

**Comment by dac09** [comment]
Thanks for raising this @danielzzz - we'll look into it :). Could I ask how important it is to have the file locally for you (and why?)? You could always late tape upload (without `--local`) and download if necessary

To be clear, we will look to fix this, just trying to understand your motivation :)

**Comment by danielzzz** [comment]
no special case, it's just if I'd need to further process it withouth having to upload it and then download it back to my pc.

thanks!

**Comment by dac09** [comment]
Hey @danielzzz, just published a potential fix for this.

You can try it if you wish, by installing the pre-release version
```
npm install -g tape-cli@next
```

Please let me know if it works for you, and I'll let you close the issue 👍

**Comment by danielzzz** [comment]
yep! it seems to be working! thank you very much!

I don't want to stretch it, but it would be great to be able to set the file name, not just a directory ;)

thanks!

**Comment by dac09** [comment]
Awesome :) - happy to be help! Please do help us get the word out by sharing with your friends/colleagues.

I'll create an issue for `local` flag enhancements, thank you for the great bug report!
