### ISSUE TITLE
Getting a TypeError: Cannot read property '0' of undefined 

### ISSUE THREAD

**Issue by nelsonchen5** [edamameldn/tape-cli#62]
Been getting this error when I try to run `tape gif --local=~/Screenshots`

 Error:
 ```
 TypeError: Cannot read property '0' of undefined``` 


---
 - **os**: darwin 
- **arch**: x64

**Comment by dac09** [comment]
Hello, thanks for raising this. Is this a problem without the local flag?

**Comment by nelsonchen5** [comment]
yup, same issue without the local flag

**Comment by dac09** [comment]
I will look into it, will report back soon. 

Would appreciate if you had any more logs, and include any more details of what you were taping. 

Thanks again!

**Comment by dac09** [comment]
Hello, @nelsonchen5  appreciate you reporting this. 

Very obscure bug on the serverside, it should be fixed now. If not please re-open the issue.

**Comment by nelsonchen5** [comment]
hi @dac09 , really appreciate the quick turnaround

however -- seeing this message now

```
 ›   Error: ENOENT: no such file or directory, copyfile '/var/folders/d9/wc5zrp
 ›   j1667b4022m87v4swr0000gp/T/AmnestiedMicrologicLordliestSurfeit.gif' ->
 ›   '~/Screenshots/AmnestiedMicrologicLordliestSurfeit.gif'
```

**Comment by dac09** [comment]
Maybe try without the equals - I'm not sure why it makes a difference, but this should work:

```
tape gif --local ~/Screenshots
```

CLI args typicall don't requires equals, but I may be wrong here!

**Comment by dac09** [comment]
Hey @nelsonchen5, hope the above solves your issue. I've created a discord server: https://discord.gg/r3VjzRCk if you would like to join, to make it a little easier to chat.

**Comment by nelsonchen5** [comment]
@dac09 neat that seems to do it!
